package database

import (
	"context"
	"testing"
	"time"

	"github.com/javinizer/javinizer-go/internal/models"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

func TestCreditRepositoriesLifecycle(t *testing.T) {
	db, service, credit, collision := collisionFixture(t)
	ctx := context.Background()
	credits, collisions := service.Credits, service.Collisions
	found, err := credits.FindByMovieAndActress(ctx, credit.MovieContentID, credit.ActressID)
	require.NoError(t, err)
	require.Equal(t, credit.ID, found.ID)
	_, err = credits.FindByMovieAndActress(ctx, "missing", credit.ActressID)
	require.ErrorIs(t, err, ErrNotFound)
	_, err = credits.FindByCreditID(ctx, 999)
	require.ErrorIs(t, err, ErrNotFound)
	require.NoError(t, credits.UpdateOrderPinned(ctx, credit.ID, 4, true))
	require.NoError(t, credits.SetDisplayForceCanonical(ctx, credit.ID, true))
	require.NoError(t, credits.MarkMovieDirty(ctx, credit.MovieContentID))
	list, err := credits.ListByActress(ctx, credit.ActressID)
	require.NoError(t, err)
	require.Len(t, list, 1)
	require.True(t, list[0].OrderPinned)
	require.Equal(t, 4, list[0].OrderIndex)
	require.True(t, list[0].DisplayForceCanonical)
	count, err := credits.CountByActress(ctx, credit.ActressID)
	require.NoError(t, err)
	require.EqualValues(t, 1, count)
	open, err := collisions.ListOpenByActress(ctx, credit.ActressID)
	require.NoError(t, err)
	require.Len(t, open, 1)
	counts, err := collisions.CountOpenByMovieBatch(ctx, []string{credit.MovieContentID, "missing"})
	require.NoError(t, err)
	require.EqualValues(t, 1, counts[credit.MovieContentID])
	require.Zero(t, counts["missing"])
	has, err := collisions.HasOpenForMovie(ctx, credit.MovieContentID)
	require.NoError(t, err)
	require.True(t, has)
	require.NoError(t, collisions.Resolve(ctx, collision.ID, models.CollisionResolutionKeepIdentity))
	has, err = collisions.HasOpenForMovie(ctx, credit.MovieContentID)
	require.NoError(t, err)
	require.False(t, has)
	require.NoError(t, collisions.Reopen(ctx, collision.ID))
	require.NoError(t, db.First(&collision, collision.ID).Error)
	require.True(t, collision.UserPinned)
	require.Empty(t, collision.Resolution)
	collision.CanonicalValue = "New Truth"
	require.NoError(t, db.Transaction(func(tx *gorm.DB) error { return collisions.RecordTx(tx, &collision, "javdb") }))
	require.Equal(t, 2, collision.Occurrences)
	require.Equal(t, "dmm,javdb", collision.SourcesSeen)
	require.NoError(t, collisions.CloseByCredit(ctx, credit.ID, models.CollisionResolutionByRemoval))
	open, err = collisions.ListOpenByMovie(ctx, credit.MovieContentID)
	require.NoError(t, err)
	require.Empty(t, open)
	require.NoError(t, db.Transaction(func(tx *gorm.DB) error { return credits.DeleteTx(tx, credit.MovieContentID, credit.ActressID) }))
	count, err = credits.CountByActress(ctx, credit.ActressID)
	require.NoError(t, err)
	require.Zero(t, count)
}

func TestCreditRepositoriesCancellationErrors(t *testing.T) {
	db, service, credit, collision := collisionFixture(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	r, c := service.Credits, service.Collisions
	_, err := r.ListByMovie(ctx, "x")
	require.Error(t, err)
	_, err = r.FindByCreditID(ctx, credit.ID)
	require.Error(t, err)
	_, err = r.FindByMovieAndActress(ctx, credit.MovieContentID, credit.ActressID)
	require.Error(t, err)
	_, err = r.ListByActress(ctx, credit.ActressID)
	require.Error(t, err)
	_, err = r.CountByActress(ctx, credit.ActressID)
	require.Error(t, err)
	require.Error(t, r.UpdateOverride(ctx, credit.ID, "x", true))
	require.Error(t, r.UpdateSuppressed(ctx, credit.ID, true))
	require.Error(t, r.UpdateOrderPinned(ctx, credit.ID, 1, true))
	require.Error(t, r.SetDisplayForceCanonical(ctx, credit.ID, true))
	require.Error(t, r.MarkMovieDirty(ctx, credit.MovieContentID))
	_, err = c.ListOpenByMovie(ctx, "x")
	require.Error(t, err)
	_, err = c.ListOpenByActress(ctx, credit.ActressID)
	require.Error(t, err)
	_, err = c.CountOpenByMovieBatch(ctx, []string{"x"})
	require.Error(t, err)
	_, err = c.HasOpenForMovie(ctx, "x")
	require.Error(t, err)
	require.Error(t, c.Resolve(ctx, collision.ID, "keep_identity"))
	require.Error(t, c.Reopen(ctx, collision.ID))
	tx := db.WithContext(ctx)
	_, err = r.ListByMovieTx(tx, "x")
	require.Error(t, err)
	_, err = c.ListOpenByMovieTx(tx, "x")
	require.Error(t, err)
	require.Error(t, r.DeleteTx(tx, "x", 1))
	require.Error(t, r.DeleteByIDTx(tx, credit.ID))
	require.Error(t, r.UpsertTx(tx, &credit))
	require.Error(t, c.RecordTx(tx, &collision, "x"))
	require.Error(t, c.ResolveTx(tx, collision.ID, "keep_identity"))
}

func TestIdentityCatalogOwnershipAndImports(t *testing.T) {
	db, service, credit, _ := collisionFixture(t)
	r := service.Actresses
	ctx := context.Background()
	require.NoError(t, r.UpdateCanonicalFields(ctx, credit.ActressID, "Edited", "Person", "名前", "thumb"))
	a, err := r.FindByID(ctx, credit.ActressID)
	require.NoError(t, err)
	require.Equal(t, "Edited", a.FirstName)
	require.True(t, a.Verified)
	require.NoError(t, r.SetUserOwned(ctx, a.ID))
	require.Error(t, r.ImportUpsert(ctx, nil))
	incoming := models.Actress{DMMID: 123, FirstName: "Import", LastName: "Person", JapaneseName: "輸入", ThumbURL: "import-thumb"}
	require.NoError(t, r.ImportUpsert(ctx, &incoming))
	require.True(t, incoming.Verified)
	require.Equal(t, ActressOriginImport, incoming.Origin)
	replacement := models.Actress{DMMID: 123, FirstName: "Wrong", LastName: "Wrong", JapaneseName: "違う", ThumbURL: "wrong"}
	require.NoError(t, r.ImportUpsert(ctx, &replacement))
	require.Equal(t, incoming.ID, replacement.ID)
	require.Equal(t, "Import", replacement.FirstName)
	require.Equal(t, "import-thumb", replacement.ThumbURL)
	byName := models.Actress{FirstName: "Import", LastName: "Person"}
	require.NoError(t, r.ImportUpsert(ctx, &byName))
	require.Equal(t, incoming.ID, byName.ID)
	empty := models.Actress{DMMID: 456, Verified: true, Origin: ActressOriginUser}
	require.NoError(t, db.Create(&empty).Error)
	fill := models.Actress{DMMID: 456, FirstName: "Filled", LastName: "Name", JapaneseName: "補完", ThumbURL: "filled"}
	require.NoError(t, r.ImportUpsert(ctx, &fill))
	require.Equal(t, empty.ID, fill.ID)
	require.Equal(t, "Filled", fill.FirstName)
	require.Equal(t, "filled", fill.ThumbURL)
	_, err = r.FindVerifiedByDMMID(ctx, 0)
	require.ErrorIs(t, err, ErrNotFound)
	_, err = r.FindVerifiedByDMMID(ctx, 999)
	require.ErrorIs(t, err, ErrNotFound)
	_, err = r.FindVerifiedByAlias(ctx, "missing")
	require.ErrorIs(t, err, ErrNotFound)
	for _, canonical := range []string{"", "absent", "Import Person"} {
		alias := models.ActressAlias{AliasName: "alias-" + canonical, CanonicalName: canonical}
		require.NoError(t, db.Create(&alias).Error)
		found, err := r.FindVerifiedByAlias(ctx, alias.AliasName)
		if canonical == "Import Person" {
			require.NoError(t, err)
			require.Equal(t, incoming.ID, found.ID)
		} else {
			require.ErrorIs(t, err, ErrNotFound)
		}
	}
	matches, err := r.FindVerifiedByExactName(ctx, "", "", "")
	require.NoError(t, err)
	require.Empty(t, matches)
	matches, err = r.FindVerifiedByExactName(ctx, "名前", "", "")
	require.NoError(t, err)
	require.Len(t, matches, 1)
	candidates, err := r.ListCandidates(ctx, 0, 0)
	require.NoError(t, err)
	require.Empty(t, candidates)
	count, err := r.CountCandidates(ctx)
	require.NoError(t, err)
	require.Zero(t, count)
	translations, err := r.FreshTranslationsByActress(ctx, a.ID)
	require.NoError(t, err)
	require.Empty(t, translations)
	r.markCreditingMoviesDirty(ctx, 0)
}

func TestIdentityCatalogCancellationErrors(t *testing.T) {
	_, service, credit, _ := collisionFixture(t)
	r := service.Actresses
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := r.FindVerifiedByDMMID(ctx, 1)
	require.Error(t, err)
	_, err = r.FindVerifiedByAlias(ctx, "x")
	require.Error(t, err)
	_, err = r.FindVerifiedByExactName(ctx, "x", "", "")
	require.Error(t, err)
	_, err = r.ListCandidates(ctx, 1, 0)
	require.Error(t, err)
	_, err = r.CountCandidates(ctx)
	require.Error(t, err)
	require.Error(t, r.PromoteCandidate(ctx, credit.ActressID, "a", "b", "c", "d"))
	require.Error(t, r.SetUserOwned(ctx, credit.ActressID))
	require.Error(t, r.UpdateCanonicalFields(ctx, credit.ActressID, "a", "b", "c", "d"))
	require.Error(t, r.ImportUpsert(ctx, &models.Actress{DMMID: 1}))
	require.Error(t, r.ImportUpsert(ctx, &models.Actress{FirstName: "x"}))
	_, err = r.DeleteStaleCandidates(ctx, time.Now())
	require.Error(t, err)
	_, err = r.FreshTranslationsByActress(ctx, credit.ActressID)
	require.Error(t, err)
	r.markCreditingMoviesDirty(ctx, credit.ActressID)
}
